Fix an error with creating a directory of a file name, which breaks the build.
--- Unwind-sjlj.o ---
In file included from /usr/home/brd/freebsd/freebsd/contrib/llvm/projects/libunwind/src/Unwind-sjlj.c:13:
/usr/home/brd/freebsd/freebsd/contrib/llvm/projects/libunwind/include/unwind.h:19:10: fatal error: 'stdint.h' file not found
 #include <stdint.h>
          ^~~~~~~~~~